# Generated by Django 3.2.5 on 2021-07-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20210722_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='bairro',
            new_name='bairro_perfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='cep',
            new_name='cep_perfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='cidade',
            new_name='cidade_perfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='complemento',
            new_name='complemento_perfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='cpf',
            new_name='cpf_perfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='data_nascimento',
            new_name='data_nascimento_perfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='endereco',
            new_name='endereco_perfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='estado',
            new_name='estado_perfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='numero',
            new_name='numero_perfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='usuario_perfil',
        ),
    ]
