# Generated by Django 3.2.5 on 2021-07-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20210725_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='bairro_perfil',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='cep_perfil',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='cidade_perfil',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='complemento_perfil',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='cpf_perfil',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='data_nascimento_perfil',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='endereco_perfil',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='estado_perfil',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='numero_perfil',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario_perfil',
            new_name='usuario',
        ),
    ]
