# Generated by Django 3.2.6 on 2021-08-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_alter_endereco_apelido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='apelido',
            field=models.CharField(help_text='Digite aqui um apelido para o endereço. Ele será usado para você identificar o endereço durante a compra', max_length=50),
        ),
    ]
