# Generated by Django 3.2.5 on 2021-07-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_marketing',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_marketing_promocional',
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
