# Generated by Django 3.2.5 on 2021-07-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20210725_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_curta',
            new_name='descricao_curta_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_longa',
            new_name='descricao_longa_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='imagem_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='slug',
            new_name='slug_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='tipo',
            new_name='tipo_produto',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='estoque',
            new_name='estoque_variacao',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='nome',
            new_name='nome_variacao',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_promocional',
            new_name='preco_promocional_variacao',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='preco',
            new_name='preco_variacao',
        ),
    ]
