# Generated by Django 3.2.5 on 2021-07-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20210725_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_curta_produto',
            new_name='descricao_curta',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_longa_produto',
            new_name='descricao_longa',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagem_produto',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome_produto',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='slug_produto',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='tipo_produto',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='estoque_variacao',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='nome_variacao',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_variacao',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_promocional_variacao',
            new_name='preco_promocional',
        ),
    ]
