# Generated by Django 3.2.5 on 2021-07-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_auto_20210725_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Preço promocional'),
        ),
    ]
