# Generated by Django 3.2.5 on 2021-07-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itempedido',
            table='item_pedido',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
    ]
