# Generated by Django 3.2.5 on 2021-07-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_alter_pedido_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='imagem',
            new_name='imagem_itempedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='pedido',
            new_name='pedido_itempedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='preco',
            new_name='preco_itempedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='preco_promocional',
            new_name='preco_promocional_itempedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='produto_id',
            new_name='produto_id_itempedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='produto',
            new_name='produto_itempedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='quantidade',
            new_name='quantidade_itempedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='variacao_id',
            new_name='variacao_id_itempedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='variacao',
            new_name='variacao_itempedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='status',
            new_name='status_pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='total',
            new_name='total_pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario',
            new_name='usuario_pedido',
        ),
        migrations.AlterModelTable(
            name='itempedido',
            table='itempedido',
        ),
    ]
