# Generated by Django 3.2.5 on 2021-07-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_auto_20210725_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='imagem_itempedido',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='pedido_itempedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='preco_itempedido',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='preco_promocional_itempedido',
            new_name='preco_promocional',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='produto_itempedido',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='produto_id_itempedido',
            new_name='produto_id',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='quantidade_itempedido',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='variacao_itempedido',
            new_name='variacao',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='variacao_id_itempedido',
            new_name='variacao_id',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='status_pedido',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='total_pedido',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario_pedido',
            new_name='usuario',
        ),
    ]
